### ISSUE TITLE
Fails to render

### ISSUE THREAD

**Issue by knock2one** [89Mods/TheGhastModdings-MIDI-Video-Generator#2]
When I try to render "MAMI ZONE Crazy mode & Maiden's Capriccio - Dream Battle 57Million[V.3]", It said "Cannot create video" or "Failed rendering". I used the pagefile mode with 100gb of hdd for a pagefile and that happened. When I get the error again, I will put an image.
Specs: ![image](https://cloud.githubusercontent.com/assets/22779352/22805895/9af2630e-eeed-11e6-8ad2-cb9f5c3269ef.png)

**Comment by 89Mods** [comment]
While pagefile mode allows you to _load_ huge MIDIs, it'll still need some RAM for rendering. Give it as much RAM as possible, even in pagefile mode. Also, the fancy notes gradient still breaks in pagefile mode on any resolution that isn't 720p, so watch out for that.

**Comment by knock2one** [comment]
Thank you, I allocated 2072mb of ram, I have 4 GB of ram, How much should I allocate before it's too much?
I also put fancy notes off (because it looks better) and I used 720p @ 60fps.

**Comment by 89Mods** [comment]
Just make sure windows has enough ram left to not freeze, like 512MB.

**Comment by Theblackmidi72** [comment]
Same thing here, The most way I rage is 90% and error comes up, I use pagefile with 4GB ram

**Comment by 89Mods** [comment]
Turns out this is a bug after all. It took me literally this long to find. I will release the update with the bugfix tomorrow.

**Comment by 89Mods** [comment]
Fixed it
