### ISSUE TITLE
You should add GPU hardware acceleration.

### ISSUE THREAD

**Issue by knock2one** [89Mods/TheGhastModdings-MIDI-Video-Generator#4]
If you add GPU Acceleration, we would be able to use our graphics and render midi's faster with this program. Then, we wouldn't have to wait 1 day to render a 2 min midi. lel.

**Comment by 89Mods** [comment]
The renderer is actualy allready very optimized, but the reason it's all so slow is because it has to encode the video frames into the video and write it onto the disk. So unless 2500Mb/sec PCIe SSDs become mainstream, there is no point.
