### ISSUE TITLE
How large midi that can make into video on my computer?

### ISSUE THREAD

**Issue by FoxyBuddy** [89Mods/TheGhastModdings-MIDI-Video-Generator#7]
My computer bought in 2011 and the system was updated to Windows 7 in 2015.
The CPU speed is 2.6GHZ and RAM is 2GB and the system is 32-bit.
How large midi that can make into video on my computer?
By the way, the Java 9 installer can be found in China? (Because I'm in a Chinese relative's home now.)

**Comment by 89Mods** [comment]
You download Java 9 from java.com, which is an english site. I don't know about China. Also, the most you can load with 2GB is 5 million notes.
